create extension if not exists pgcrypto with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default '',
  role text not null default 'member' check (role in ('admin', 'member')),
  membership_status text not null default 'inactive' check (membership_status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.site_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table public.ebooks (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  subtitle text not null default '',
  description text not null default '',
  regular_price text not null default '',
  sale_price text not null default '',
  purchase_url text not null default '',
  cover_image text not null default '',
  sort_order integer not null default 0,
  is_published boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.member_resources (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('class', 'activity', 'audio', 'guide', 'resource')),
  month_label text not null default '',
  title text not null,
  description text not null default '',
  url text not null default '',
  sort_order integer not null default 0,
  is_published boolean not null default false,
  updated_at timestamptz not null default now()
);

create index ebooks_sort_idx on public.ebooks (sort_order, id);
create index resources_sort_idx on public.member_resources (sort_order, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute procedure public.set_updated_at();

create trigger ebooks_set_updated_at
before update on public.ebooks
for each row execute procedure public.set_updated_at();

create trigger resources_set_updated_at
before update on public.member_resources
for each row execute procedure public.set_updated_at();

create or replace function public.is_configured_admin(candidate_email text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select encode(extensions.digest(lower(coalesce(candidate_email, '')), 'sha256'), 'hex') in (
    'd39fbb8efec67734e84ded9c9c8c3b5510444d10c19c00e82cf58f75bd17ce7a',
    '716e2f12c9e441a2cedea94e6c22d6746507b8c03e838f22d750738f0680e93c'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name, role, membership_status)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''),
    case when public.is_configured_admin(new.email) then 'admin' else 'member' end,
    case when public.is_configured_admin(new.email) then 'active' else 'inactive' end
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = case when excluded.display_name <> '' then excluded.display_name else public.profiles.display_name end,
    role = case when public.is_configured_admin(excluded.email) then 'admin' else public.profiles.role end,
    membership_status = case when public.is_configured_admin(excluded.email) then 'active' else public.profiles.membership_status end;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email, display_name, role, membership_status)
select
  id,
  lower(coalesce(email, '')),
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name', ''),
  case when public.is_configured_admin(email) then 'admin' else 'member' end,
  case when public.is_configured_admin(email) then 'active' else 'inactive' end
from auth.users
on conflict (id) do update set
  email = excluded.email,
  role = case when public.is_configured_admin(excluded.email) then 'admin' else public.profiles.role end,
  membership_status = case when public.is_configured_admin(excluded.email) then 'active' else public.profiles.membership_status end;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create or replace function public.has_active_membership()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and (role = 'admin' or membership_status = 'active')
  );
$$;

revoke all on function public.is_configured_admin(text) from public;
revoke all on function public.handle_new_user() from public;
revoke all on function public.set_updated_at() from public;
revoke all on function public.is_admin() from public;
revoke all on function public.has_active_membership() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.has_active_membership() to authenticated;

alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.ebooks enable row level security;
alter table public.member_resources enable row level security;

create policy "Users read their own profile"
on public.profiles for select to authenticated
using (id = (select auth.uid()));

create policy "Admins manage profiles"
on public.profiles for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Public reads settings"
on public.site_settings for select to anon, authenticated
using (true);

create policy "Admins manage settings"
on public.site_settings for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Public reads published ebooks"
on public.ebooks for select to anon, authenticated
using (is_published);

create policy "Admins manage ebooks"
on public.ebooks for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Active members read published resources"
on public.member_resources for select to authenticated
using (is_published and (select public.has_active_membership()));

create policy "Admins manage resources"
on public.member_resources for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant usage on schema public to anon, authenticated;
grant select on public.site_settings, public.ebooks to anon;
grant select, insert, update, delete on public.profiles, public.site_settings, public.ebooks, public.member_resources to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.site_settings (key, value) values
  ('hero_eyebrow', 'Coaching ontológico para mujeres'),
  ('hero_title', 'Salí a comerte el mundo'),
  ('hero_subtitle', 'No sos lo que te pasó. Sos lo que vas a hacer con todo eso. Te acompaño a dejar de postergarte y volver a elegirte.'),
  ('story_title', 'Toqué fondo y elegí levantarme.'),
  ('story_body', 'Hubo una etapa en la que me sentí perdida, apagada, sin saber para dónde ir. Desde ese lugar tomé la decisión más difícil: dejar de esperar que alguien me rescatara y empezar a moverme yo. Hoy acompaño a otras mujeres a hacer exactamente eso.'),
  ('membership_title', 'Bienvenidas a bordo'),
  ('membership_body', 'Un espacio mensual para sentirte más segura, confiar en tus decisiones y aprender a elegirte sin dar explicaciones.'),
  ('membership_price_regular', '$70.000'),
  ('membership_price_sale', '$51.999'),
  ('membership_purchase_url', ''),
  ('current_theme', 'Reconstruir mi valor'),
  ('current_theme_description', 'Un mes para reconocer lo que valés y sostenerlo, aunque nadie te lo confirme.'),
  ('next_session_label', 'Sábado · 19:00 h'),
  ('next_session_url', ''),
  ('whatsapp_url', 'https://wa.me/5492964406552'),
  ('instagram_url', 'https://instagram.com/maricelconse')
on conflict (key) do nothing;

insert into public.ebooks
  (slug, title, subtitle, description, regular_price, sale_price, purchase_url, cover_image, sort_order, is_published)
values
  ('equipaje-liviano', 'Equipaje liviano', 'Soltar lo que pesa para volver a vos.', 'Para reconocer qué estás cargando, qué no te toca y cómo empezar a soltarlo sin culpa.', '$24.999', '$15.999', '', '/images/ebook-equipaje-liviano.jpg', 1, true),
  ('el-destino-sos-vos', 'El destino sos vos', 'Encontrar tu rumbo cuando perdiste el norte.', 'Cinco pasos para dejar de seguir el mapa de otros, escuchar tu brújula y dar un paso propio.', '$24.999', '$15.999', '', '/images/ebook-el-destino-sos-vos.jpg', 2, true),
  ('sin-turbulencias', 'Sin turbulencias', 'Calma para habitarte sin pelearla.', 'Herramientas simples para atravesar la ansiedad, volver al presente y tratarte con más calma.', '$24.999', '$15.999', '', '/images/ebook-sin-turbulencias.jpg', 3, true),
  ('el-cielo-no-es-el-limite', 'El cielo no es el límite', 'Animarte a soñar sin ponerte techo.', 'Para revisar ese techo invisible y bajar tu sueño grande a un primer paso concreto, con fecha.', '$24.999', '$15.999', '', '/images/ebook-el-cielo-no-es-el-limite.jpg', 4, true)
on conflict (slug) do nothing;

insert into public.member_resources
  (kind, month_label, title, description, url, sort_order, is_published)
select 'guide', 'Primeros pasos', 'Guía de viaje: cómo funciona este espacio', 'Un recorrido rápido para encontrar cada recurso sin perderte.', '/guia-de-viaje', 1, true
where not exists (
  select 1 from public.member_resources where title = 'Guía de viaje: cómo funciona este espacio'
);
