create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'mercadopago' check (provider = 'mercadopago'),
  provider_subscription_id text not null unique,
  provider_plan_id text,
  external_reference text not null,
  payer_email text not null,
  checkout_url text,
  status text not null default 'pending',
  payment_status text not null default 'pending',
  access_until timestamptz,
  next_payment_date timestamptz,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamptz,
  last_provider_update_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.subscription_events (
  id bigint generated by default as identity primary key,
  provider_event_key text not null unique,
  topic text not null,
  action text not null default '',
  provider_resource_id text not null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);

create index subscriptions_profile_idx
on public.subscriptions (profile_id, created_at desc);

create index subscriptions_access_idx
on public.subscriptions (profile_id, access_until desc);

create index subscription_events_resource_idx
on public.subscription_events (topic, provider_resource_id);

create trigger subscriptions_set_updated_at
before update on public.subscriptions
for each row execute procedure public.set_updated_at();

alter table public.subscriptions enable row level security;
alter table public.subscription_events enable row level security;

create policy "Members read their subscriptions"
on public.subscriptions for select to authenticated
using (profile_id = (select auth.uid()));

create policy "Admins manage subscriptions"
on public.subscriptions for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Admins read subscription events"
on public.subscription_events for select to authenticated
using ((select public.is_admin()));

grant select on public.subscriptions to authenticated;
grant select on public.subscription_events to authenticated;

create or replace function public.has_active_membership()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and (
        p.role = 'admin'
        or exists (
          select 1
          from public.subscriptions s
          where s.profile_id = p.id
            and s.access_until > now()
        )
        or (
          p.membership_status = 'active'
          and not exists (
            select 1
            from public.subscriptions existing_subscription
            where existing_subscription.profile_id = p.id
          )
        )
      )
  );
$$;

revoke all on function public.has_active_membership() from public;
grant execute on function public.has_active_membership() to authenticated;
